ALTER TABLE "agents" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "agents" ALTER COLUMN "project_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "audit_log" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "conversations" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "conversations" ALTER COLUMN "project_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "deployments" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "deployments" ALTER COLUMN "environment_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "deployments" ALTER COLUMN "release_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "draft_changes" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "draft_changes" ALTER COLUMN "project_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "draft_changes" ALTER COLUMN "agent_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "environments" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "environments" ALTER COLUMN "project_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "environments" ALTER COLUMN "agent_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "github_installations" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "ingest_tokens" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "ingest_tokens" ALTER COLUMN "project_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "jobs" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "releases" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "releases" ALTER COLUMN "project_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "releases" ALTER COLUMN "agent_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "run_steps" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "run_steps" ALTER COLUMN "run_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "runs" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "runs" ALTER COLUMN "project_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "runs" ALTER COLUMN "agent_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "runs" ALTER COLUMN "deployment_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "runs" ALTER COLUMN "release_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "runs" ALTER COLUMN "session_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "schedules" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "schedules" ALTER COLUMN "deployment_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "secret_values" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "secret_values" ALTER COLUMN "project_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "secret_values" ALTER COLUMN "agent_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "secret_values" ALTER COLUMN "environment_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "secrets_metadata" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "secrets_metadata" ALTER COLUMN "project_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "secrets_metadata" ALTER COLUMN "agent_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "secrets_metadata" ALTER COLUMN "environment_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "project_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "agent_id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "usage_events" ALTER COLUMN "id" SET DATA TYPE varchar(12);--> statement-breakpoint
ALTER TABLE "usage_events" ALTER COLUMN "deployment_id" SET DATA TYPE varchar(12);