import { mobileApi } from "@eden/api-contract";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { EmptyState, ErrorState, Loading, colors, useNativeTheme } from "@/components/native";
import { useApiResource } from "@/hooks/use-api-resource";

type Template={id:string;type:string;name:string;description:string;version?:string};type Data={templates:Template[];installed:string[];catalogError:string|null};
const filters=["all","installed","agent","skill","tool","channel","bundle"];
export default function MarketplaceScreen(){const t=useNativeTheme();const{data,error,loading,refresh}=useApiResource<Data>(mobileApi.marketplace());const[query,setQuery]=useState("");const[filter,setFilter]=useState("all");const shown=useMemo(()=>{const installed=new Set(data?.installed??[]);return(data?.templates??[]).filter(x=>(filter==="all"||filter==="installed"?filter!=="installed"||installed.has(`${x.type}/${x.id}`):x.type===filter)&&(`${x.name} ${x.description}`).toLowerCase().includes(query.toLowerCase()))},[data,filter,query]);if(loading&&!data)return <Loading label="Opening catalog…"/>;if(error&&!data)return <View style={{padding:16}}><ErrorState message={error} onRetry={refresh}/></View>;return <FlatList style={{backgroundColor:t.background}} contentContainerStyle={styles.list} data={shown} keyExtractor={x=>`${x.type}/${x.id}`} refreshControl={<RefreshControl refreshing={false} onRefresh={refresh} tintColor={colors.blue}/>} ListHeaderComponent={<View style={styles.header}><TextInput accessibilityLabel="Search templates" placeholder="Search templates" placeholderTextColor={t.muted} value={query} onChangeText={setQuery} style={[styles.search,{backgroundColor:t.surface,borderColor:t.border,color:t.text}]}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map(x=><Pressable key={x} onPress={()=>setFilter(x)} style={[styles.chip,{backgroundColor:filter===x?colors.blue:t.surface,borderColor:filter===x?colors.blue:t.border}]}><Text style={{color:filter===x?"#fff":t.text,textTransform:"capitalize",fontWeight:"600"}}>{x}</Text></Pressable>)}</ScrollView>{data?.catalogError?<ErrorState message={data.catalogError}/>:null}</View>} ListEmptyComponent={!data?.catalogError?<EmptyState title="Nothing found" message="Try another search or category."/>:null} renderItem={({item})=><Pressable accessibilityRole="button" onPress={()=>router.push(`/(app)/(tabs)/marketplace/${item.type}/${item.id}`)} style={({pressed})=>[styles.card,{backgroundColor:t.surface,borderColor:t.border,opacity:pressed?.7:1}]}><View style={styles.cardTop}><Text style={[styles.name,{color:t.text}]}>{item.name}</Text><Text style={[styles.badge,{color:colors.blue,backgroundColor:t.dark?"#172554":"#dbeafe"}]}>{item.type}</Text></View><Text style={{color:t.muted,lineHeight:20}}>{item.description}</Text>{item.version?<Text style={{color:t.muted,fontSize:12}}>v{item.version}</Text>:null}</Pressable>}/>}
const styles=StyleSheet.create({list:{padding:16,gap:10,flexGrow:1},header:{gap:12,marginBottom:6},search:{height:48,borderWidth:1,borderRadius:12,paddingHorizontal:14,fontSize:16},filters:{gap:8},chip:{height:38,paddingHorizontal:14,borderRadius:19,borderWidth:1,justifyContent:"center"},card:{padding:16,borderRadius:14,borderWidth:StyleSheet.hairlineWidth,gap:8},cardTop:{flexDirection:"row",justifyContent:"space-between",gap:10},name:{fontSize:17,fontWeight:"700",flex:1},badge:{paddingHorizontal:9,paddingVertical:4,borderRadius:10,fontSize:11,fontWeight:"700",textTransform:"uppercase"}});
