/**
 * The generated `eden-model.ts` workspace module — the single place a repo's agents (and
 * subagents) resolve their model, plus the matching `agent.ts` scaffold.
 *
 * The module exports ONE function, `edenAgentModel(agentName)`, used verbatim in every agent
 * file: `model: edenAgentModel('<agent-name>')`. No agent file ever carries a model string.
 * Per step it resolves, in order:
 *
 *   1. the playground's signed per-conversation directive (model switching), else
 *   2. Eden's workspace configuration (`GET <EDEN_MODEL_GATEWAY_URL>/model-config`) — the
 *      org's explicit per-agent override when one exists, else the workspace default model.
 *
 * A workspace with nothing configured produces a readable "set a model in Org settings"
 * error — by design, never a silent fallback. Subagents pass their PARENT agent's name, so a
 * parent and its subagents always run the same model; a configuration change in Eden reaches
 * running agents on their next step with no code change and no redeploy.
 *
 * The module reuses the exact generated building blocks `setModel` injects into legacy
 * modules (`EDEN_MODEL_HELPER`: the directive parser + the `edenModel` credential router), so
 * the two generations cannot drift on routing behavior.
 */
import {
  DEFAULT_MODEL_CONTEXT_WINDOW_TOKENS,
  EDEN_GATEWAY_FACTORY,
  EDEN_MODEL_HELPER,
  OPENROUTER_FACTORY,
} from "~/eve/agentModule";

export const ORG_MODEL_MODULE_FILENAME = "eden-model.ts";

/** The module path for a member root, e.g. `agents/bob/agent` → `agents/bob/agent/eden-model.ts`. */
export function orgModelModulePath(root: string): string {
  return `${root}/${ORG_MODEL_MODULE_FILENAME}`;
}

/**
 * The import specifier for `eden-model.ts` from a file at `depth` directories below the member
 * root: the member's `agent.ts` sits at depth 0 (`./eden-model`), a subagent's `agent.ts` at
 * depth 2 (`../../eden-model` — `subagents/<name>/agent.ts`).
 */
export function orgModelImportSpecifier(depth = 0): string {
  return depth <= 0 ? "./eden-model" : `${"../".repeat(depth)}eden-model`;
}

const MODULE_HEADER = `// eden-model.ts — generated by Eden. The one place this repo's agents resolve their model.
//
// \`edenAgentModel('<agent-name>')\` resolves per step:
//   1. the playground's signed per-conversation directive (model switching), else
//   2. the workspace's configured model for that agent name from Eden — the org's explicit
//      per-agent override when one exists, else the workspace default model.
// Nothing configured is a readable error (set a model in Eden's Org settings), never a silent
// fallback. Subagents pass their PARENT agent's name, so a parent and its subagents always run
// the same model. Configuration changes in Eden reach a running agent on its next step — no
// code change, no redeploy.
import { createHmac, timingSafeEqual } from 'node:crypto';
import { createAnthropic } from '@ai-sdk/anthropic';
import { createOpenAI } from '@ai-sdk/openai';
import { createOpenAICompatible } from '@ai-sdk/openai-compatible';
import { wrapLanguageModel, type LanguageModel } from 'ai';
import { defineDynamic } from 'eve';

`;

const CONFIG_SECTION = `// ── Workspace model configuration (Eden control plane) ────────────────────────
type EdenReasoningEffort = 'none' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
interface EdenModelConfig {
  model: string;
  effort: EdenReasoningEffort | null;
  contextWindowTokens: number | null;
}
// Cached briefly so a burst of steps doesn't hammer the control plane; a configuration change
// in Eden still lands on a running agent within the TTL.
const EDEN_MODEL_CONFIG_TTL_MS = 30_000;
const edenModelConfigCache = new Map<string, { at: number; config: EdenModelConfig }>();

async function edenConfiguredModel(agentName: string): Promise<EdenModelConfig> {
  const cached = edenModelConfigCache.get(agentName);
  if (cached && Date.now() - cached.at < EDEN_MODEL_CONFIG_TTL_MS) return cached.config;
  const base = process.env.EDEN_MODEL_GATEWAY_URL;
  const token = process.env.EDEN_MODEL_GATEWAY_TOKEN;
  if (!base || !token) {
    throw new Error(
      'This build has no Eden model coordinates (EDEN_MODEL_GATEWAY_URL / EDEN_MODEL_GATEWAY_TOKEN) — redeploy the agent from Eden.',
    );
  }
  let response: Awaited<ReturnType<typeof fetch>>;
  try {
    response = await fetch(base + '/model-config?agent=' + encodeURIComponent(agentName), {
      headers: { authorization: 'Bearer ' + token },
    });
  } catch (error) {
    throw new Error(
      'Could not reach Eden to resolve the model for "' + agentName + '": ' +
        (error instanceof Error ? error.message : String(error)),
    );
  }
  const body = (await response.json().catch(() => null)) as {
    model?: string;
    effort?: EdenReasoningEffort | null;
    contextWindowTokens?: number | null;
    error?: { message?: string };
  } | null;
  if (!response.ok || !body || typeof body.model !== 'string') {
    throw new Error(
      body?.error?.message ?? 'Eden model-config returned HTTP ' + response.status + '.',
    );
  }
  const config: EdenModelConfig = {
    model: body.model,
    effort: body.effort ?? null,
    contextWindowTokens: body.contextWindowTokens ?? null,
  };
  edenModelConfigCache.set(agentName, { at: Date.now(), config });
  return config;
}

/**
 * The model slot for the agent (or subagent) named \`agentName\`. Subagents MUST pass their
 * parent agent's name — that is what keeps a team on one configured model. The fallback below
 * is build-time metadata only; every served step resolves through the event handler.
 */
export function edenAgentModel(agentName: string) {
  return defineDynamic({
    fallback: wrapLanguageModel({
      model: openrouter.chatModel('eden/unconfigured'),
      middleware: {
        specificationVersion: 'v4',
        transformParams: async () => {
          throw new Error(
            'The model for "' + agentName + '" resolves from Eden\\'s workspace configuration at ' +
              'each step; this build-time fallback cannot serve requests. Set a model in ' +
              'Eden\\'s Org settings.',
          );
        },
      },
    }),
    events: {
      'step.started': async (_event, ctx) => {
        const selected = edenSelectedModel(ctx.messages);
        if (selected) {
          return {
            model: edenModel(selected.id, selected.effort),
            modelContextWindowTokens: selected.contextWindowTokens,
          };
        }
        const configured = await edenConfiguredModel(agentName);
        return {
          model: edenModel(configured.model, configured.effort ?? undefined),
          modelContextWindowTokens: configured.contextWindowTokens ?? undefined,
        };
      },
    },
  });
}
`;

/** The complete generated `eden-model.ts` content. */
export function orgModelModuleSource(): string {
  return `${MODULE_HEADER}${OPENROUTER_FACTORY}${EDEN_GATEWAY_FACTORY}\n${EDEN_MODEL_HELPER}\n${CONFIG_SECTION}`;
}

/**
 * A fresh `agent.ts` for an agent named `agentName` — no model string anywhere; the workspace
 * configuration is the source of truth from day one.
 */
export function scaffoldOrgModelAgentModule(agentName: string): string {
  const safe = agentName.replace(/['"`\\]/g, "");
  return `import { defineAgent } from 'eve';

import { edenAgentModel } from '${orgModelImportSpecifier()}';

export default defineAgent({
  model: edenAgentModel('${safe}'),
  modelContextWindowTokens: ${DEFAULT_MODEL_CONTEXT_WINDOW_TOKENS},
});
`;
}
