import { mobileApi } from "@eden/api-contract";
import { router } from "expo-router";
import { useState } from "react";
import { FlatList, RefreshControl, StyleSheet, Text, View } from "react-native";
import { Button, EmptyState, ErrorState, Heading, Loading, Row, SectionTitle, colors, useNativeTheme } from "@/components/native";
import { useApiResource } from "@/hooks/use-api-resource";

type Project={id:string;name:string;repoOwner:string|null;repoName:string|null;defaultBranch:string;layout:string};type Card={project:Project;members:string[];isTeam:boolean};type Dashboard={org:{id:string;name:string}|null;cards:Card[]};
export default function DashboardScreen(){const t=useNativeTheme();const{data,error,loading,refresh}=useApiResource<Dashboard>(mobileApi.dashboard());const[refreshing,setRefreshing]=useState(false);const reload=async()=>{setRefreshing(true);await refresh();setRefreshing(false)};if(loading&&!data)return <Loading label="Loading repositories…"/>;if(error&&!data)return <View style={styles.pad}><ErrorState message={error} onRetry={refresh}/></View>;const cards=data?.cards??[];return <FlatList style={{backgroundColor:t.background}} contentContainerStyle={styles.list} data={cards} keyExtractor={item=>item.project.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload} tintColor={colors.blue}/>} ListHeaderComponent={<View style={styles.header}><Heading title="Repositories" subtitle={data?.org?`${data.org.name} · Your agents and teams`:"Your agents and teams"}/><Button title="Connect repository" onPress={()=>router.push("/(app)/connect")}/>{error?<Text style={{color:colors.red}}>{error}</Text>:null}{cards.length?<SectionTitle>Workspace repositories</SectionTitle>:null}</View>} ListEmptyComponent={<EmptyState title="No repositories yet" message="Connect an existing eve repository or create a fresh one." action={<Button title="Get started" onPress={()=>router.push("/(app)/connect")}/>}/>} renderItem={({item})=><View style={[styles.item,{backgroundColor:t.surface,borderColor:t.border}]}><Row title={item.project.name} detail={item.project.repoOwner?`${item.project.repoOwner}/${item.project.repoName} · ${item.project.defaultBranch}`:`No GitHub repository · ${item.project.defaultBranch}`} meta={item.isTeam?`${item.members.length} agents`:"Agent"} onPress={()=>router.push(`/(app)/repos/${item.project.id}`)}/>{item.isTeam&&item.members.length?<Text numberOfLines={1} style={{color:t.muted,fontSize:12,paddingBottom:10}}>{item.members.join(" · ")}</Text>:null}</View>}/>}
const styles=StyleSheet.create({pad:{padding:16},list:{padding:16,gap:10,flexGrow:1},header:{gap:14,marginBottom:6},item:{borderWidth:StyleSheet.hairlineWidth,borderRadius:14,paddingHorizontal:14,overflow:"hidden"}});
