/**
 * eve repo → Docker image build pipeline (validated end-to-end in docs/SPIKE-EVE.md).
 *
 * Fetch the repo tarball at a commit (GitHub App) → extract to a scratch dir → ensure Eden's
 * reference multi-stage Dockerfile (respecting one the repo already has) → `docker build`.
 *
 * Two images are produced per build:
 *   <tag>        runtime — Nitro .output only (small, what actually runs)
 *   <tag>-build  the full build stage (node_modules incl. @workflow/world-postgres) — kept
 *                because the world's migration CLI (`workflow-postgres-setup`) is NOT traced
 *                into .output; per-instance DB setup runs from this image at deploy time.
 *
 * The build runs entirely inside linux containers, so the host needs Docker but not Node 24
 * or the eve toolchain, and native modules are traced for the right platform.
 */
import { execFile } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { promisify } from "node:util";

import { getInstallationOctokit } from "~/github/client.server";
import type { BuiltArtifact } from "~/seams/types";

const exec = promisify(execFile);

/**
 * Reference multi-stage Dockerfile for an eve agent. The build stage must keep full
 * node_modules (see module docs); the runtime stage ships only the Nitro output.
 */
const EDEN_EVE_DOCKERFILE = `# Generated by Eden (reference eve agent image).
FROM node:24-slim AS build
WORKDIR /app
COPY package*.json ./
RUN if [ -f package-lock.json ]; then npm ci --no-audit --no-fund; else npm install --no-audit --no-fund; fi
COPY . .
RUN npm exec -- eve build

FROM node:24-slim
WORKDIR /app
COPY --from=build /app/.output ./.output
ENV PORT=3000
EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]
`;

const EDEN_DOCKERIGNORE = `node_modules
.output
.eve
.git
`;

/** Runtime + build-stage tags for a project@commit. Local (unregistried) for dev. */
function imageTags(projectId: string, ref: string) {
  const tag = `eden/proj-${projectId.slice(0, 8)}:${ref.slice(0, 12)}`;
  return { runtime: tag, buildStage: `${tag}-build` };
}

/** The build-stage tag for a runtime imageRef (where the world migration CLI lives). */
export function buildStageTagFor(imageRef: string): string {
  return `${imageRef}-build`;
}

export interface EveImageBuildInput {
  projectId: string;
  repo: { owner: string; repo: string };
  /** Commit SHA to build (a Release's merge commit). */
  ref: string;
  /** GitHub App installation that can read the repo. */
  installationId: string | number;
}

/** Fetch repo@ref, ensure Dockerfile, docker-build runtime + build-stage images. */
export async function buildEveImage(input: EveImageBuildInput): Promise<BuiltArtifact> {
  const workDir = await mkdtemp(path.join(tmpdir(), "eden-build-"));
  try {
    // 1. Repo tarball at the exact commit (GitHub App installation token).
    const octokit = await getInstallationOctokit(input.installationId);
    const res = await octokit.request("GET /repos/{owner}/{repo}/tarball/{ref}", {
      owner: input.repo.owner,
      repo: input.repo.repo,
      ref: input.ref,
    });
    const tarPath = path.join(workDir, "src.tar.gz");
    await writeFile(tarPath, Buffer.from(res.data as ArrayBuffer));
    const srcDir = path.join(workDir, "src");
    await exec("mkdir", ["-p", srcDir]);
    // GitHub tarballs wrap everything in a single "<owner>-<repo>-<sha>/" directory.
    await exec("tar", ["-xzf", tarPath, "-C", srcDir, "--strip-components=1"]);

    // 2. Eden's reference Dockerfile, unless the repo brings its own.
    if (!existsSync(path.join(srcDir, "Dockerfile"))) {
      await writeFile(path.join(srcDir, "Dockerfile"), EDEN_EVE_DOCKERFILE);
    }
    if (!existsSync(path.join(srcDir, ".dockerignore"))) {
      await writeFile(path.join(srcDir, ".dockerignore"), EDEN_DOCKERIGNORE);
    }

    // 3. Build both images (the runtime build reuses the build stage from cache).
    const tags = imageTags(input.projectId, input.ref);
    const opts = { maxBuffer: 64 * 1024 * 1024 };
    await exec("docker", ["build", "--target", "build", "-t", tags.buildStage, srcDir], opts);
    const { stderr: buildLog } = await exec(
      "docker",
      ["build", "-t", tags.runtime, srcDir],
      opts,
    );

    const { stdout: digest } = await exec("docker", [
      "inspect",
      "--format",
      "{{.Id}}",
      tags.runtime,
    ]);
    return { imageRef: tags.runtime, digest: digest.trim(), logs: buildLog };
  } finally {
    await rm(workDir, { recursive: true, force: true });
  }
}
